[package]
name = "top"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.7"
gilrs = "0.8"
nalgebra = "0.29"
mint = "0.5"
rand = "0.8"  # or the version you are using
rand_distr = "0.4"
noise = "0.7"
tokio = { version = "1", features = ["full"] }
mini-redis = "0.4"
bytes = "1"
crossterm = "0.27.0"
console = "0.15.7"
local-ip-address = "0.5.6"
